# Generated by Django 3.0.6 on 2020-05-25 13:15

from django.db import migrations
from baseball.models import Sport
from StadiumTrackerAPI.settings import DEBUG
import requests


def load_sports(apps, schema_editor):
    if not DEBUG:
        sports = requests.get('http://statsapi.mlb.com/api/v1/sports').json()['sports']
        for s in sports:
            Sport(mlb_api_sports_id=s['id'],
                  code=s['code'],
                  name=s['name'],
                  abbreviation=s['abbreviation'],
                  sort_order=s['sortOrder'],
                  active=s['activeStatus']).save()


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0001_squashed_0004_auto_20200523_2359'),
    ]

    operations = [
        migrations.RunPython(load_sports),
    ]
