# Generated by Django 3.0.6 on 2020-05-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_content_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content", name="slug", field=models.SlugField(),
        ),
    ]
