# Generated by Django 3.0.5 on 2020-04-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stadium_tracker", "0009_auto_20191008_0349"),
    ]

    operations = [
        migrations.RemoveField(model_name="gamesseen", name="user",),
        migrations.DeleteModel(name="Venues",),
        migrations.AlterModelOptions(
            name="gamedetails", options={"ordering": ["user", "-game_datetime"]},
        ),
        migrations.DeleteModel(name="GamesSeen",),
    ]
