# Generated by Django 3.0.6 on 2020-05-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0010_auto_20200426_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='view_type',
            field=models.CharField(choices=[('T', 'Television'), ('P', 'In Person')], default='P', max_length=1),
        ),
    ]
