# Generated by Django 3.0.6 on 2020-05-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0012_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='mlb_api_league_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
