# Generated by Django 3.0.6 on 2020-05-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0014_auto_20200519_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_division_id', models.IntegerField()),
                ('division_name', models.CharField(max_length=255)),
                ('mlb_api_sport_id', models.IntegerField()),
                ('has_wildcard', models.BooleanField()),
                ('mlb_api_league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.League')),
            ],
        ),
    ]
