# Generated by Django 3.0.6 on 2020-05-20 02:12

from django.db import migrations
import requests
from stadium_tracker.league_details import get_leagues
from stadium_tracker.models import League


def load_leagues(apps, schema_editor):
    for league in get_leagues():
        League(mlb_api_league_id=league['id'],
                league_name=league['name'],
                ).save()



class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0016_auto_20200520_0210'),
    ]

    operations = [
        migrations.RunPython(load_leagues),
    ]
