# Generated by Django 3.0.6 on 2020-05-22 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0020_auto_20200520_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_venue_id', models.IntegerField()),
                ('venue_name', models.CharField(max_length=255)),
            ],
        ),
    ]
