# Generated by Django 3.0.6 on 2020-05-22 01:26

from django.db import migrations
import requests
from stadium_tracker.models import Venue


def load_venues(apps, schema_editor):
    url = 'http://statsapi.mlb.com/api/v1/venues'
    r = requests.get(url)
    venues = r.json().get("venues")
    for v in venues:
        Venue(mlb_api_venue_id=v['id'], venue_name=v['name']).save()


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0021_venue'),
    ]

    operations = [
        migrations.RunPython(load_venues),
    ]
