# Generated by Django 3.0.6 on 2020-05-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0022_auto_20200522_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_team_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('team_code', models.CharField(max_length=255)),
                ('file_code', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('first_year_of_play', models.IntegerField()),
                ('short_name', models.CharField(max_length=255)),
                ('all_star_status', models.BooleanField()),
                ('active', models.BooleanField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Division')),
                ('parent_organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Team')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.League')),
                ('spring_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spring_league', to='stadium_tracker.League')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Venue')),
            ],
        ),
    ]
