# Generated by Django 3.0.6 on 2020-05-23 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0023_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetails',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Venue'),
        ),

    ]
