# Generated by Django 3.0.6 on 2020-05-23 23:59

from django.db import migrations
from baseball.models import Venue
from stadium_tracker.models import GameDetails


def update_venues(apps, schema_editor):
    for g in GameDetails.objects.all():
        v = Venue.objects.filter(mlb_api_venue_id=g.venue_id)
        g.stadium = v.first()
        g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0025_auto_20200523_2359'),
    ]

    operations = [
        migrations.RunPython(update_venues),
    ]
