# Generated by Django 3.0.6 on 2020-05-26 00:49

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0026_auto_20200523_2359'),
    ]

    operations = [
        migrations.DeleteModel("Team")
    ]
