# Generated by Django 3.0.6 on 2020-05-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0027_auto_20200526_0049'),
    ]

    operations = [
        migrations.DeleteModel("Venue"),
        migrations.DeleteModel("Division"),
        migrations.DeleteModel("League"),
    ]
