# Generated by Django 3.0.6 on 2020-05-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadium_tracker', '0028_auto_20200526_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_division_id', models.IntegerField()),
                ('division_name', models.CharField(max_length=255)),
                ('mlb_api_league_id', models.IntegerField()),
                ('has_wildcard', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_venue_id', models.IntegerField()),
                ('venue_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlb_api_team_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('team_code', models.CharField(max_length=255)),
                ('file_code', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('first_year_of_play', models.IntegerField()),
                ('short_name', models.CharField(max_length=255)),
                ('all_star_status', models.BooleanField()),
                ('active', models.BooleanField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Division')),
                ('parent_organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Team')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.League')),
                ('spring_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spring_league', to='stadium_tracker.League')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.Venue')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='mlb_api_sport_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium_tracker.League'),
        ),
        migrations.DeleteModel("Team"),
        migrations.DeleteModel("Venue"),
        migrations.DeleteModel("Division"),
        migrations.DeleteModel("League")
    ]
